############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/01/2020        #
############################
name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u eliasdh-com --password-stdin
      - name: Build/Push Frontend Docker Image
        run: |
          docker build --push -t ghcr.io/eliasdh-com/eliasdhcom-frontend:latest ./